### ISSUE TITLE
Samples for [pus] Pashto

### ISSUE THREAD

**Issue by ufo-boy** [larsyencken/wide-language-index#116]
- https://youtu.be/iOAF4t_umM8?t=11s

- https://youtu.be/QbVw1wF7st4?t=45s

- https://youtu.be/CQEUB-EZHiE?t=8s

- https://youtu.be/8TC57zsksgg?t=11s

- https://youtu.be/toK-o4QSWcI

- https://youtu.be/NOqrE3t1SmE

**Comment by larsyencken** [comment]
Added to the index!
