### ISSUE TITLE
Samples in [yor] Yoruba

### ISSUE THREAD

**Issue by Giovani93** [larsyencken/wide-language-index#121]
-  https://www.youtube.com/watch?v=jiS4LEMaziU
-  https://www.youtube.com/watch?v=ZRxgjmsyIdk
-  https://www.youtube.com/watch?v=dlJu2_LfrDk

And lastly, sorry for this, but I don't know, how to put bullet on one line and link to another line, everything is at one line. I don't know, where to ask this question, so I must here.

**Comment by Giovani93** [comment]
-    https://www.youtube.com/watch?v=jiS4LEMaziU
-    https://www.youtube.com/watch?v=ZRxgjmsyIdk
-    https://www.youtube.com/watch?v=dlJu2_LfrDk

**Comment by Giovani93** [comment]
Really, I don't know, how to do those things, like I have seen here, as I mentioned.

**Comment by larsyencken** [comment]
No worries, thanks for the language samples!

**Comment by larsyencken** [comment]
I added these three to the index just now: https://github.com/larsyencken/wide-language-index/commit/bbf760c34a27caa861c6e44f415a19367aba3e9b

 When I have time, I'll try to find some good snippets and get them into the game too. Thanks again!
