### ISSUE TITLE
Ossetic sample

### ISSUE THREAD

**Issue by amikeco** [larsyencken/wide-language-index#30]
Ossetic (Ossetian) samples can be taken in mp3 from http://ironau.ru/audioarxiv.html
All are local radio records, professional voices. News for 15 Aug 2009 for example: http://i.ironau.ru/mp3/20090815.mp3
Thank you for the game.

**Comment by larsyencken** [comment]
Thank you! I just added several of these samples to the language index, they'll let me put Ossetic into the game.
