### ISSUE TITLE
One of the Uzbek samples...

### ISSUE THREAD

**Issue by jaulie** [larsyencken/wide-language-index#34]
One of the Uzbek samples contains a good amount of Russian in the beginning and then switches to Uzbek.

**Comment by larsyencken** [comment]
Thanks for reporting it. Did you listen to it in the Great Language Game? If so, do you know which one of these it was? (They're all short, so hopefully it only takes a few moments to check each one.)

1. https://greatlanguagegame.com/static/audio/uzn/uzn-13ab4484ae74aef73f1eb304e8043cb3-0-20.mp3
2. https://greatlanguagegame.com/static/audio/uzn/uzn-1ee5cc36dee8781f817fef642ec560ef-480-500.mp3
3. https://greatlanguagegame.com/static/audio/uzn/uzn-5022fa54b5a32ec99227b02a31d1eb83-1320-1340.mp3
4. https://greatlanguagegame.com/static/audio/uzn/uzn-a7ebfb951b98d98e56b573de29df0e82-160-180.mp3
5. https://greatlanguagegame.com/static/audio/uzn/uzn-ac1529c6225eb70c7d75c682f3183717-600-620.mp3
6. https://greatlanguagegame.com/static/audio/uzn/uzn-c5e18c212a94a65178e405a4dca1542a-460-480.mp3
7. https://greatlanguagegame.com/static/audio/uzn/uzn-cde284a165b05439aa1bda7e73c0e890-460-480.mp3
8. https://greatlanguagegame.com/static/audio/uzn/uzn-cfe57d32aa3c254be68767c19f4fcea8-220-240.mp3
9. https://greatlanguagegame.com/static/audio/uzn/uzn-e5cfda22b767948d2707e39402494f79-160-180.mp3
10. https://greatlanguagegame.com/static/audio/uzn/uzn-effb15e6a04068d1c10580eada351ae1-820-840.mp3

**Comment by larsyencken** [comment]
Unfortunately, I don't have the expertise to work this out myself. Closing the issue for now.

**Comment by larsyencken** [comment]
Got help from someone, it was number 3. Fixing it...
