### ISSUE TITLE
Somali clip from BBC

### ISSUE THREAD

**Issue by XxAnonXx** [larsyencken/wide-language-index#37]
http://www.bbc.com/somali/maqal_iyo_muuqaal/2016/07/160721_somalia_aids

**Comment by larsyencken** [comment]
Thank you, I added it:

Record: https://github.com/larsyencken/wide-language-index/blob/master/index/som/som-b18b705f7c00bbcdbf5ad9a2a482db1a.json

Audio: http://mirror.widelanguageindex.org/som/som-b18b705f7c00bbcdbf5ad9a2a482db1a.mp3
