### ISSUE TITLE
Hungarian language sample

### ISSUE THREAD

**Issue by szentemark** [larsyencken/wide-language-index#39]
**File information**

Sample URL: [http://mek.oszk.hu/03100/03172/mp3/2188af01.mp3](http://mek.oszk.hu/03100/03172/mp3/2188af01.mp3)
Length: 26:49
File size: 8MB
Format: mp3

**Text information**

The text is from a novel of a popular Hungarian writer called Rejtő Jenő.

Language: Hungarian
Author: Rejtő Jenő
English Wikipedia page: [https://en.wikipedia.org/wiki/Jen%C5%91_Rejt%C5%91](https://en.wikipedia.org/wiki/Jen%C5%91_Rejt%C5%91)
Novel title: A 14 karátos autó
English title: The 14-Carat Roadster
Chapter: 1st
URL listing all other chapters: [http://mek.oszk.hu/03100/03172/mp3/](http://mek.oszk.hu/03100/03172/mp3/)

**Copyright information**

[http://mek.oszk.hu](http://mek.oszk.hu) is a community based collection of literature resources in Hungarian language. According to the website terms of use information, all material is free to use for personal and educational non-profit purposes.

According to the Hungarian Copyrights Office, as of January 1st, 2014, the works of Rejtő Jenő are no longer under copyright protection, as copyright protection only applies for 70 years after the death of the author.

**Comment by larsyencken** [comment]
Thanks so much! I added all chapters of this book to the index.
