### ISSUE TITLE
Samples in Xhosa

### ISSUE THREAD

**Issue by ufo-boy** [larsyencken/wide-language-index#87]
Xhosa one of the official languages of South Africa and it also uses click sounds.
- https://youtu.be/hUKB2ipD7xw?t=2s

- https://youtu.be/Z25DYD0TljM

- https://youtu.be/5iXdIOkWb4g?t=8s

- https://youtu.be/ufS1I-GvfFs?t=24s

- https://youtu.be/rijv5B01JDM?t=8s

- https://youtu.be/2Zm2TtSxbWw

- https://youtu.be/PKhBrMpyx1M?t=15s

- https://youtu.be/NYnmr939snU?t=2s

- https://youtu.be/dF1CdKk_mm8

- https://youtu.be/Zq9UDaCa6Lw?t=8s

- https://iono.fm/e/417410?autoplay=1

**Comment by larsyencken** [comment]
Added them to the index: https://github.com/larsyencken/wide-language-index/pull/101

Thanks so much!

**Comment by larsyencken** [comment]
And now added to the game as well 🔥
