### ISSUE TITLE
Samples for [ell] Greek

### ISSUE THREAD

**Issue by ufo-boy** [larsyencken/wide-language-index#92]
- https://youtu.be/McDocRtfHLI

- https://youtu.be/vWhis3Qf5y0

- https://youtu.be/FbEKOVyMCvQ

- https://youtu.be/T62SU3w7mLM

- https://youtu.be/9FwbsfTslR8

- https://youtu.be/S6NFckcrnFA?t=3s

- https://youtu.be/FCBq7As_GPI

- https://youtu.be/SniAy6ezTuM

- https://youtu.be/XFVKsghoUEQ

- https://youtu.be/fBVZMABXBMQ?t=1m57s

**Comment by larsyencken** [comment]
Added them to the index! The next step is to listen to enough to add them to the game too.

You can see today's sample count for different languages here: https://github.com/larsyencken/wide-language-index/blob/master/STATS.md

Thanks so much for tagging the languages with codes, I really appreciated it!
