### ISSUE TITLE
Samples for Mongolian

### ISSUE THREAD

**Issue by ufo-boy** [larsyencken/wide-language-index#93]
- https://youtu.be/1Vg5bGYVrzw

- https://youtu.be/HmpXkr6z3FI?t=8s

- https://youtu.be/SGEKKr-TMfU?t=55s

- https://youtu.be/UNgUdFtcT4k

- https://youtu.be/BNRnoLm9k70?t=47s

- https://youtu.be/neb2vacBQmk

- https://youtu.be/LOBLEGoNz0g?t=33s

- https://youtu.be/nf-CaiLQxvQ

**Comment by Giovani93** [comment]
Hi!
Here is another sample of mongolian.
- https://www.youtube.com/watch?v=olWIaG1sy1o

**Comment by larsyencken** [comment]
Added these to the index just now, thank you both!
