### ISSUE TITLE
Samples in Nepali

### ISSUE THREAD

**Issue by ufo-boy** [larsyencken/wide-language-index#96]
- https://youtu.be/MKP9kShRYa0?t=1m5s

- https://youtu.be/imtvCZIg9Z4

- https://youtu.be/0XSyJUDbJ2k

- https://youtu.be/H1_tskEgetE?t=24s

- https://youtu.be/Ntr-aDMjcJ8?t=6s

- http://media.sbs.com.au/audio/nepalese_170702_709630.mp3

- https://youtu.be/x0bvLzZwhv4

- http://www.bbc.co.uk/programmes/p054j6c4

**Comment by larsyencken** [comment]
Added the Youtube ones. Thanks!
